project_id = "jwlimmeijpfmaksvmuru"

[functions.sync-adversus]
verify_jwt = false

[functions.adversus-webhook]
verify_jwt = false

[functions.import-products]
verify_jwt = false

[functions.economic-webhook]
verify_jwt = false

[functions.sync-economic]
verify_jwt = false

[functions.finance-summary]
verify_jwt = false

[functions.cleanup-inactive-employees]
verify_jwt = false
