import type { RouteConfig } from "./types";
import {
  Auth,
  Home,
  Dashboard,
  Agents,
  Sales,
  Payroll,
  Settings,
  
  MgTest,
  MgTestDashboard,
  KmTest,
  Codan,
  TdcErhverv,
  TdcErhvervDashboard,
  RelatelDashboard,
  NotFound,
  AdversusData,
  DialerData,
  CallsData,
  Logikker,
  EmployeeMasterData,
  EmployeeDetail,
  EmployeeOnboarding,
  VagtFlowIndex,
  VagtBookWeek,
  VagtLocations,
  VagtBookings,
  VagtMinUge,
  VagtVehicles,
  VagtTimeOffRequests,
  VagtLocationDetail,
  VagtBilling,
  VagtSalesRegistration,
  ShiftOverview,
  MySchedule,
  AbsenceManagement,
  TimeTracking,
  Contracts,
  MyContracts,
  ContractSign,
  PulseSurvey,
  PulseSurveyResults,
  PublicPulseSurvey,
  MyProfile,
  CareerWishes,
  CareerWishesOverview,
  CarQuiz,
  CarQuizAdmin,
  CodeOfConduct,
  CodeOfConductAdmin,
  ExtraWork,
  ExtraWorkAdmin,
  RecruitmentDashboard,
  RecruitmentCandidates,
  CandidateDetail,
  RecruitmentMessages,
  SmsTemplates,
  EmailTemplatesPage,
  Winback,
  UpcomingInterviews,
  UpcomingHires,
  Some,
  TimeStamp,
  TestBoard,
  EconomicBoard,
  ClientSalesOverview,
  SalesDashboard,
  ClosingShifts,
  Permissions,
  RolePreview,
} from "./pages";
import { SmartRedirect } from "./guards";

export const routes: RouteConfig[] = [
  { path: "/", component: SmartRedirect, access: "public" },
  { path: "/auth", component: Auth, access: "auth" },
  { path: "/onboarding", component: EmployeeOnboarding, access: "public" },

  { path: "/home", component: Home, access: "protected" },
  { path: "/my-schedule", component: MySchedule, access: "protected" },
  { path: "/my-profile", component: MyProfile, access: "protected" },
  { path: "/my-contracts", component: MyContracts, access: "protected" },
  { path: "/pulse-survey", component: PulseSurvey, access: "protected" },
  { path: "/career-wishes", component: CareerWishes, access: "protected" },
  { path: "/car-quiz", component: CarQuiz, access: "protected" },
  { path: "/code-of-conduct", component: CodeOfConduct, access: "protected" },
  { path: "/time-stamp", component: TimeStamp, access: "protected" },
  { path: "/extra-work", component: ExtraWork, access: "protected" },
  { path: "/some", component: Some, access: "protected" },

  { path: "/contract/:id", component: ContractSign, access: "public" },
  { path: "/contract/sign/:id", component: ContractSign, access: "public" },

  { path: "/dashboard", component: Dashboard, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_dashboard" },
  { path: "/agents", component: Agents, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_employees" },
  { path: "/sales", component: Sales, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_sales" },
  { path: "/codan", component: Codan, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_codan" },
  { path: "/tdc-erhverv", component: TdcErhverv, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_tdc_erhverv" },
  { path: "/tdc-erhverv-dashboard", component: TdcErhvervDashboard, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_tdc_erhverv" },
  { path: "/relatel-dashboard", component: RelatelDashboard, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_mg_test" },
  
  { path: "/payroll", component: Payroll, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_payroll" },
  { path: "/mg-test", component: MgTest, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_mg_test" },
  { path: "/mg-test-dashboard", component: MgTestDashboard, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_test_dashboard" },
  { path: "/km-test", component: KmTest, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_km_test" },
  { path: "/adversus-data", component: AdversusData, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_adversus_data" },
  { path: "/dialer-data", component: DialerData, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_dialer_data" },
  { path: "/calls-data", component: CallsData, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_calls_data" },
  { path: "/logikker", component: Logikker, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_logics" },
  { path: "/employees", component: EmployeeMasterData, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_employees" },
  { path: "/employees/:id", component: EmployeeDetail, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_employees" },
  
  { path: "/settings", component: Settings, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_settings" },

  {
    path: "/vagt-flow",
    component: VagtFlowIndex,
    access: "role",
    requireTeamlederOrAbove: true,
    positionPermission: "menu_fm_overview",
    children: [
      { path: "book-week", component: VagtBookWeek, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_book_week" },
      { path: "locations", component: VagtLocations, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_locations" },
      { path: "locations/:id", component: VagtLocationDetail, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_locations" },
      { path: "bookings", component: VagtBookings, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_bookings" },
      { path: "vehicles", component: VagtVehicles, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_vehicles" },
      { path: "time-off", component: VagtTimeOffRequests, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_time_off" },
      { path: "sales-registration", component: VagtSalesRegistration, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_overview" },
      { path: "billing", component: VagtBilling, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_fm_billing" },
      { path: "min-uge", component: VagtMinUge, access: "protected" },
    ],
  },

  {
    path: "/shift-planning",
    component: ShiftOverview,
    access: "role",
    requireTeamlederOrAbove: true,
    positionPermission: "menu_shift_overview",
    children: [
      { path: "my-schedule", component: MySchedule, access: "protected" },
      { path: "absence", component: AbsenceManagement, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_absence" },
      { path: "time-tracking", component: TimeTracking, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_time_tracking" },
    ],
  },

  { path: "/extra-work-admin", component: ExtraWorkAdmin, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_extra_work_admin" },
  { path: "/contracts", component: Contracts, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_contracts" },
  { path: "/pulse-survey-results", component: PulseSurveyResults, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_pulse_survey" },
  { path: "/career-wishes-overview", component: CareerWishesOverview, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_career_wishes_overview" },
  { path: "/car-quiz-admin", component: CarQuizAdmin, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_car_quiz_admin" },
  { path: "/code-of-conduct-admin", component: CodeOfConductAdmin, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_coc_admin" },

  {
    path: "/recruitment",
    component: RecruitmentDashboard,
    access: "role",
    requireTeamlederOrAbove: true,
    positionPermission: "menu_recruitment_dashboard",
    children: [
      { path: "candidates", component: RecruitmentCandidates, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_candidates" },
      { path: "candidates/:id", component: CandidateDetail, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_candidates" },
      { path: "messages", component: RecruitmentMessages, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_messages" },
      { path: "sms-templates", component: SmsTemplates, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_sms_templates" },
      { path: "email-templates", component: EmailTemplatesPage, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_email_templates" },
      { path: "winback", component: Winback, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_winback" },
      { path: "upcoming-interviews", component: UpcomingInterviews, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_upcoming_interviews" },
      { path: "upcoming-hires", component: UpcomingHires, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_upcoming_hires" },
    ],
  },

  { path: "/boards/test", component: TestBoard, access: "public" },
  { path: "/boards/economic", component: EconomicBoard, access: "public" },
  { path: "/client-sales-overview", component: ClientSalesOverview, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_sales" },
  { path: "/boards/sales", component: SalesDashboard, access: "public" },
  { path: "/survey", component: PublicPulseSurvey, access: "public" },

  { path: "/closing-shifts", component: ClosingShifts, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_closing_shifts" },

  { path: "/permissions", component: Permissions, access: "role", requiredRole: "ejer", positionPermission: "menu_permissions" },
  { path: "/role-preview/:id", component: RolePreview, access: "role", requireTeamlederOrAbove: true, positionPermission: "menu_permissions" },
  { path: "*", component: NotFound, access: "public" },
];
