import type { RouteConfig } from "./types";
import { MyScheduleRedirect, MyGoalsRedirect, MyContractsRedirect, CareerWishesRedirect } from "./redirects";
import {
  Auth,
  Home,
  Dashboard,
  Agents,
  Sales,
  Settings,
  MgTest,
  TdcErhvervDashboard,
  RelatelDashboard,
  RelatelProductsDashboard,
  NotFound,
  Logikker,
  EmployeeMasterData,
  EmployeeDetail,
  EmployeeOnboarding,
  ResetPassword,
  VagtFlowIndex,
  VagtBookWeek,
  VagtLocations,
  VagtBookings,
  VagtBookingManagement,
  VagtVehicles,
  VagtTimeOffRequests,
  VagtLocationDetail,
  VagtBilling,
  VagtSalesRegistration,
  VagtTravelExpenses,
  VagtEditSalesRegistrations,
  MyBookingSchedule,
  ShiftOverview,
  MySchedule,
  AbsenceManagement,
  TimeTracking,
  Contracts,
  MyContracts,
  ContractSign,
  PulseSurvey,
  PulseSurveyResults,
  PublicPulseSurvey,
  MyProfile,
  MyGoals,
  CareerWishes,
  CareerWishesOverview,
  CarQuiz,
  CarQuizAdmin,
  CodeOfConduct,
  CodeOfConductAdmin,
  ExtraWork,
  ExtraWorkAdmin,
  RecruitmentDashboard,
  RecruitmentCandidates,
  CandidateDetail,
  RecruitmentMessages,
  SmsTemplates,
  EmailTemplatesPage,
  Winback,
  UpcomingInterviews,
  UpcomingHires,
  Some,
  TimeStamp,
  ClientSalesOverview,
  SalesDashboard,
  ClosingShifts,
  Permissions,
  SystemEmailTemplates,
  CompanyOverview,
  RolePreview,
  LoginLog,
  EesyTmDashboard,
  UnitedDashboard,
  CsTop20Dashboard,
  DashboardHome,
  FieldmarketingDashboardFull,
  CphSalesDashboard,
  DashboardSettings,
  DesignDashboard,
  SalesOverviewAll,
  Messages,
  OnboardingAdmin,
  OnboardingDashboard,
  OnboardingCourse,
  MyFeedback,
  ExcelFieldMatcher,
  TvBoardLogin,
  TvBoardView,
  TvBoardAdmin,
  TvBoardDirect,
  LiveStats,
  HeadToHead,
  CoachingTemplates,
  ReferAFriend,
  PublicReferralForm,
  Referrals,
  ReportsAdmin,
  ReportsManagement,
  ReportsEmployee,
  DailyReports,
  RevenueByClient,
  SecurityDashboard,
  UpcomingStarts,
  SalarySchemes,
  CommissionLeague,
  KpiDefinitions,
  SalaryTypes,
  TdcOpsummering,
  TdcOpsummeringPublic,
  ImmediatePaymentASE,
  EconomicUpload,
  EconomicLayout,
  EconomicDashboard,
  EconomicExpenses,
  EconomicBudget,
  EconomicMapping,
  EconomicPosteringer,
  EconomicRevenueMatch,
  SalesValidation,
  Cancellations,
  SystemStability,
  TeamGoals,
  OnboardingAnalyse,
  AmoDashboard,
  AmoPlaceholder,
  AmoOrganisation,
  AmoMeetings,
  AmoAnnualDiscussion,
  AmoApv,
  AmoKemiApv,
  AmoTraining,
  AmoDocuments,
  AmoTasks,
  AmoAuditLog,
  AmoSettings,
  CustomerInquiries,
  TvLeagueDashboard,
  ClientForecast,
  ClientForecastDetail,
  PowerdagBoard,
  PowerdagInput,
  PowerdagAdmin,
  SystemFeedback,
  ComplianceOverview,
  ComplianceEmployeePrivacy,
  ComplianceInternalProcesses,
  ComplianceAdminDocumentation,
  ComplianceNotifications,
  ComplianceProcessingActivities,
  ComplianceSecurityIncidents,
} from "./pages";
import { SmartRedirect } from "./guards";

export const routes: RouteConfig[] = [
  { path: "/", component: SmartRedirect, access: "public" },
  { path: "/auth", component: Auth, access: "auth" },
  { path: "/onboarding", component: EmployeeOnboarding, access: "public" },
  { path: "/reset-password", component: ResetPassword, access: "public" },

  { path: "/home", component: Home, access: "role", positionPermission: "menu_home" },
  { path: "/head-to-head", component: HeadToHead, access: "role", positionPermission: "menu_h2h" },
  
  { path: "/my-schedule", component: MyScheduleRedirect, access: "protected" },
  { path: "/my-profile", component: MyProfile, access: "role", positionPermission: "menu_my_profile" },
  { path: "/my-goals", component: MyGoals, access: "role", positionPermission: "menu_my_goals" },
  { path: "/my-goals/:employeeId", component: MyGoals, access: "role", positionPermission: "menu_my_goals" },
  { path: "/team-goals", component: TeamGoals, access: "role", positionPermission: "menu_team_goals" },
  { path: "/my-contracts", component: MyContractsRedirect, access: "protected" },
  { path: "/pulse-survey", component: PulseSurvey, access: "protected" },
  { path: "/career-wishes", component: CareerWishesRedirect, access: "protected" },
  { path: "/car-quiz", component: CarQuiz, access: "protected" },
  { path: "/code-of-conduct", component: CodeOfConduct, access: "protected" },
  { path: "/time-stamp", component: TimeStamp, access: "role", positionPermission: "menu_time_stamp" },
  { path: "/extra-work", component: ExtraWork, access: "role", positionPermission: "menu_extra_work" },
  { path: "/some", component: Some, access: "role", positionPermission: "menu_some" },
  { path: "/messages", component: Messages, access: "role", positionPermission: "menu_messages_personal" },
  { path: "/refer-a-friend", component: ReferAFriend, access: "role", positionPermission: "menu_refer_a_friend" },
  { path: "/immediate-payment-ase", component: ImmediatePaymentASE, access: "protected" },
  { path: "/commission-league", component: CommissionLeague, access: "role", positionPermission: "menu_commission_league" },
  

  { path: "/refer/:code", component: PublicReferralForm, access: "public" },
  { path: "/tdc-public", component: TdcOpsummeringPublic, access: "public" },
  { path: "/contract/:id", component: ContractSign, access: "public" },
  { path: "/contract/sign/:id", component: ContractSign, access: "public" },

  { path: "/dashboard", component: Dashboard, access: "role", positionPermission: "menu_dashboard" },
  { path: "/agents", component: Agents, access: "role", positionPermission: "menu_employees" },
  { path: "/sales", component: Sales, access: "role", positionPermission: "menu_sales" },

  { path: "/mg-test", component: MgTest, access: "role", positionPermission: "menu_mg_test" },

  { path: "/logikker", component: Logikker, access: "role", positionPermission: "menu_logics" },
  { path: "/employees", component: EmployeeMasterData, access: "role", positionPermission: "menu_employees" },
  { path: "/employees/:id", component: EmployeeDetail, access: "role", positionPermission: "menu_employees" },
  { path: "/login-log", component: LoginLog, access: "role", positionPermission: "menu_login_log" },
  { path: "/upcoming-starts", component: UpcomingStarts, access: "role", positionPermission: "menu_upcoming_starts" },

  { path: "/settings", component: Settings, access: "role", positionPermission: "menu_settings" },

  { path: "/vagt-flow/my-schedule", component: MyBookingSchedule, access: "role", positionPermission: "menu_fm_my_schedule" },
  { path: "/vagt-flow", component: VagtFlowIndex, access: "role", positionPermission: "menu_fm_overview" },
  {
    path: "/vagt-flow/booking",
    component: VagtBookingManagement,
    access: "role",
    positionPermission: "menu_fm_booking",
  },
  { path: "/vagt-flow/book-week", component: VagtBookWeek, access: "role", positionPermission: "menu_fm_book_week" },
  { path: "/vagt-flow/locations", component: VagtLocations, access: "role", positionPermission: "menu_fm_locations" },
  {
    path: "/vagt-flow/locations/:id",
    component: VagtLocationDetail,
    access: "role",
    positionPermission: "menu_fm_locations",
  },
  { path: "/vagt-flow/bookings", component: VagtBookings, access: "role", positionPermission: "menu_fm_bookings" },
  { path: "/vagt-flow/vehicles", component: VagtVehicles, access: "role", positionPermission: "menu_fm_vehicles" },
  {
    path: "/vagt-flow/time-off",
    component: VagtTimeOffRequests,
    access: "role",
    positionPermission: "menu_fm_time_off",
  },
  {
    path: "/vagt-flow/sales-registration",
    component: VagtSalesRegistration,
    access: "role",
    positionPermission: "menu_fm_sales_registration",
  },
  { path: "/vagt-flow/billing", component: VagtBilling, access: "role", positionPermission: "menu_fm_billing" },
  { path: "/vagt-flow/travel-expenses", component: VagtTravelExpenses, access: "role", positionPermission: "menu_fm_travel_expenses" },
  { path: "/vagt-flow/edit-sales", component: VagtEditSalesRegistrations, access: "role", positionPermission: "menu_fm_edit_sales" },

  { path: "/shift-planning", component: ShiftOverview, access: "role", positionPermission: "menu_shift_overview" },
  { path: "/shift-planning/my-schedule", component: MySchedule, access: "protected" },
  { path: "/shift-planning/absence", component: AbsenceManagement, access: "role", positionPermission: "menu_absence" },
  {
    path: "/shift-planning/time-tracking",
    component: TimeTracking,
    access: "role",
    positionPermission: "menu_time_tracking",
  },

  { path: "/extra-work-admin", component: ExtraWorkAdmin, access: "role", positionPermission: "menu_extra_work_admin" },
  { path: "/contracts", component: Contracts, access: "role", positionPermission: "menu_contracts" },
  { path: "/company-overview", component: CompanyOverview, access: "role", positionPermission: "menu_contracts" },
  { path: "/onboarding-analyse", component: OnboardingAnalyse, access: "role", positionPermission: "menu_contracts" },
  { path: "/email-templates", component: SystemEmailTemplates, access: "role", positionPermission: "menu_contracts" },
  {
    path: "/pulse-survey-results",
    component: PulseSurveyResults,
    access: "role",
    positionPermission: "menu_pulse_survey",
  },
  {
    path: "/career-wishes-overview",
    component: CareerWishesOverview,
    access: "role",
    positionPermission: "menu_career_wishes_overview",
  },
  { path: "/customer-inquiries", component: CustomerInquiries, access: "role", positionPermission: "menu_customer_inquiries" },
  
  // Client Forecast
  { path: "/client-forecast", component: ClientForecast, access: "role", positionPermission: "menu_client_forecast" },
  { path: "/client-forecast/:id", component: ClientForecastDetail, access: "role", positionPermission: "menu_client_forecast" },
  { path: "/car-quiz-admin", component: CarQuizAdmin, access: "role", positionPermission: "menu_car_quiz_admin" },
  {
    path: "/code-of-conduct-admin",
    component: CodeOfConductAdmin,
    access: "role",
    positionPermission: "menu_coc_admin",
  },

  {
    path: "/recruitment",
    component: RecruitmentDashboard,
    access: "role",
    positionPermission: "menu_recruitment_dashboard",
  },
  {
    path: "/recruitment/candidates",
    component: RecruitmentCandidates,
    access: "role",
    positionPermission: "menu_candidates",
  },
  {
    path: "/recruitment/candidates/:id",
    component: CandidateDetail,
    access: "role",
    positionPermission: "menu_candidates",
  },
  {
    path: "/recruitment/messages",
    component: RecruitmentMessages,
    access: "role",
    positionPermission: "menu_messages",
  },
  {
    path: "/recruitment/sms-templates",
    component: SmsTemplates,
    access: "role",
    positionPermission: "menu_sms_templates",
  },
  {
    path: "/recruitment/email-templates",
    component: EmailTemplatesPage,
    access: "role",
    positionPermission: "menu_email_templates",
  },
  { path: "/recruitment/winback", component: Winback, access: "role", positionPermission: "menu_winback" },
  {
    path: "/recruitment/upcoming-interviews",
    component: UpcomingInterviews,
    access: "role",
    positionPermission: "menu_upcoming_interviews",
  },
  {
    path: "/recruitment/upcoming-hires",
    component: UpcomingHires,
    access: "role",
    positionPermission: "menu_upcoming_hires",
  },
  {
    path: "/recruitment/referrals",
    component: Referrals,
    access: "role",
    positionPermission: "menu_candidates",
  },

  { path: "/client-sales-overview", component: ClientSalesOverview, access: "role", positionPermission: "menu_sales" },
  { path: "/boards/sales", component: SalesDashboard, access: "protected" },

  // Dashboard Landing Page
  { path: "/dashboards", component: DashboardHome, access: "protected" },

  // Team Dashboards - access controlled at runtime via useRequireDashboardAccess hook
  { path: "/dashboards/cph-sales", component: CphSalesDashboard, access: "protected" },
  { path: "/dashboards/fieldmarketing", component: FieldmarketingDashboardFull, access: "protected" },
  { path: "/dashboards/tdc-erhverv", component: TdcErhvervDashboard, access: "protected" },
  { path: "/dashboards/relatel", component: RelatelDashboard, access: "protected" },
  { path: "/dashboards/relatel-products", component: RelatelProductsDashboard, access: "protected" },
  { path: "/dashboards/eesy-tm", component: EesyTmDashboard, access: "protected" },
  { path: "/dashboards/united", component: UnitedDashboard, access: "protected" },
  { path: "/dashboards/cs-top-20", component: CsTop20Dashboard, access: "protected" },
  { path: "/dashboards/sales-overview-all", component: SalesOverviewAll, access: "protected" },
  { path: "/dashboards/commission-league", component: TvLeagueDashboard, access: "protected" },
  { path: "/dashboards/powerdag", component: PowerdagBoard, access: "role", positionPermission: "menu_dashboard_powerdag" },
  { path: "/dashboards/powerdag/input", component: PowerdagInput, access: "role", positionPermission: "menu_powerdag_input" },
  { path: "/dashboards/powerdag/admin", component: PowerdagAdmin, access: "role", positionPermission: "menu_powerdag_input" },

  // Dashboard Admin pages - restricted to those with dashboard admin permission
  { path: "/dashboards/settings", component: DashboardSettings, access: "role", positionPermission: "menu_dashboard_admin" },
  { path: "/dashboards/design", component: DesignDashboard, access: "role", positionPermission: "menu_dashboard_admin" },

  { path: "/survey", component: PublicPulseSurvey, access: "public" },

  { path: "/closing-shifts", component: ClosingShifts, access: "role", positionPermission: "menu_closing_shifts" },

  { path: "/permissions", component: Permissions, access: "role", positionPermission: "menu_permissions" },
  { path: "/role-preview/:id", component: RolePreview, access: "role", positionPermission: "menu_permissions" },

  // Onboarding
  {
    path: "/onboarding-program",
    component: OnboardingDashboard,
    access: "role",
    positionPermission: "menu_onboarding_admin",
  },
  { path: "/onboarding-program/kursus", component: OnboardingCourse, access: "protected" },
  { path: "/my-feedback", component: MyFeedback, access: "role", positionPermission: "menu_my_feedback" },
  { path: "/coaching-templates", component: CoachingTemplates, access: "role", positionPermission: "menu_onboarding_admin" },

  { path: "/excel-field-matcher", component: ExcelFieldMatcher, access: "protected" },

  // TV Board routes
  { path: "/t/:code", component: TvBoardDirect, access: "public" },
  { path: "/tv", component: TvBoardLogin, access: "public" },
  { path: "/tv/:slug", component: TvBoardView, access: "public" },
  { path: "/tv-board-admin", component: TvBoardAdmin, access: "role", positionPermission: "menu_settings" },

  // Live Stats (hidden from sidebar, accessible via URL only)
  { path: "/live-stats", component: LiveStats, access: "protected" },

  // Reports
  { path: "/reports/admin", component: ReportsAdmin, access: "role", positionPermission: "menu_reports_admin" },
  { path: "/reports/management", component: ReportsManagement, access: "role", positionPermission: "menu_reports_management" },
  { path: "/reports/employee", component: ReportsEmployee, access: "role", positionPermission: "menu_reports_employee" },
  { path: "/reports/daily", component: DailyReports, access: "role", positionPermission: "menu_reports_daily" },
  { path: "/reports/revenue-by-client", component: RevenueByClient, access: "role", positionPermission: "menu_reports_revenue_by_client" },

  // Security Dashboard
  { path: "/admin/security", component: SecurityDashboard, access: "role", positionPermission: "menu_security_dashboard" },

  // System Stability (integration health dashboard)
  { path: "/system-stability", component: SystemStability, access: "role", positionPermission: "menu_security_dashboard" },


  // KPI Definitions (Owner only)
  { path: "/admin/kpi-definitions", component: KpiDefinitions, access: "role", positionPermission: "menu_kpi_definitions" },

  // Salary
  { path: "/salary/types", component: SalaryTypes, access: "role", positionPermission: "menu_salary_types" },
  { path: "/salary/cancellations", component: Cancellations, access: "role", positionPermission: "menu_cancellations" },

  // TDC Opsummering
  { path: "/tdc-opsummering", component: TdcOpsummering, access: "role", positionPermission: "menu_tdc_opsummering" },

  // Economic Upload (Owner only)
  { path: "/admin/economic-upload", component: EconomicUpload, access: "role", positionPermission: "menu_economic_upload" },

  // Economic Dashboard (with nested routes)
  { path: "/economic", component: EconomicDashboard, access: "role", positionPermission: "menu_economic_dashboard" },
  { path: "/economic/posteringer", component: EconomicPosteringer, access: "role", positionPermission: "menu_economic_dashboard" },
  { path: "/economic/expenses", component: EconomicExpenses, access: "role", positionPermission: "menu_economic_expenses" },
  { path: "/economic/budget", component: EconomicBudget, access: "role", positionPermission: "menu_economic_budget" },
  { path: "/economic/mapping", component: EconomicMapping, access: "role", positionPermission: "menu_economic_mapping" },
  { path: "/economic/revenue-match", component: EconomicRevenueMatch, access: "role", positionPermission: "menu_economic_dashboard" },
  { path: "/economic/sales-validation", component: SalesValidation, access: "role", positionPermission: "menu_economic_dashboard" },


  // AMO Compliance Hub
  { path: "/amo", component: AmoDashboard, access: "role", positionPermission: "menu_amo_dashboard" },
  { path: "/amo/organisation", component: AmoOrganisation, access: "role", positionPermission: "menu_amo_organisation" },
  { path: "/amo/annual-discussion", component: AmoAnnualDiscussion, access: "role", positionPermission: "menu_amo_annual_discussion" },
  { path: "/amo/meetings", component: AmoMeetings, access: "role", positionPermission: "menu_amo_meetings" },
  { path: "/amo/apv", component: AmoApv, access: "role", positionPermission: "menu_amo_apv" },
  { path: "/amo/kemi-apv", component: AmoKemiApv, access: "role", positionPermission: "menu_amo_kemi_apv" },
  { path: "/amo/training", component: AmoTraining, access: "role", positionPermission: "menu_amo_training" },
  { path: "/amo/documents", component: AmoDocuments, access: "role", positionPermission: "menu_amo_documents" },
  { path: "/amo/tasks", component: AmoTasks, access: "role", positionPermission: "menu_amo_tasks" },
  { path: "/amo/settings", component: AmoSettings, access: "role", positionPermission: "menu_amo_settings" },
  { path: "/amo/audit-log", component: AmoAuditLog, access: "role", positionPermission: "menu_amo_audit_log" },

  // System Feedback
  { path: "/system-feedback", component: SystemFeedback, access: "protected" },

  // Compliance
  { path: "/compliance", component: ComplianceOverview, access: "role", positionPermission: "menu_compliance_overview" },
  { path: "/compliance/employee-privacy", component: ComplianceEmployeePrivacy, access: "role", positionPermission: "menu_compliance_employee" },
  { path: "/compliance/processes", component: ComplianceInternalProcesses, access: "role", positionPermission: "menu_compliance_processes" },
  { path: "/compliance/admin", component: ComplianceAdminDocumentation, access: "role", positionPermission: "menu_compliance_admin" },
  { path: "/compliance/notifications", component: ComplianceNotifications, access: "role", positionPermission: "menu_compliance_admin" },
  { path: "/compliance/processing-activities", component: ComplianceProcessingActivities, access: "role", positionPermission: "menu_compliance_admin" },
  { path: "/compliance/security-incidents", component: ComplianceSecurityIncidents, access: "role", positionPermission: "menu_compliance_admin" },

  { path: "*", component: NotFound, access: "public" },
];
