import type { RouteConfig } from "./types";
import {
  Auth,
  Home,
  Dashboard,
  Agents,
  Sales,
  Payroll,
  Settings,
  
  MgTest,
  MgTestDashboard,
  KmTest,
  Codan,
  TdcErhverv,
  TdcErhvervDashboard,
  RelatelDashboard,
  TrygDashboard,
  AseDashboard,
  TeamOverview,
  NotFound,
  AdversusData,
  DialerData,
  CallsData,
  Logikker,
  EmployeeMasterData,
  EmployeeDetail,
  EmployeeOnboarding,
  ResetPassword,
  VagtFlowIndex,
  VagtBookWeek,
  VagtLocations,
  VagtBookings,
  VagtBookingManagement,
  VagtMinUge,
  VagtVehicles,
  VagtTimeOffRequests,
  VagtLocationDetail,
  VagtBilling,
  VagtSalesRegistration,
  VagtFieldmarketingDashboard,
  ShiftOverview,
  MySchedule,
  AbsenceManagement,
  TimeTracking,
  Contracts,
  MyContracts,
  ContractSign,
  PulseSurvey,
  PulseSurveyResults,
  PublicPulseSurvey,
  MyProfile,
  CareerWishes,
  CareerWishesOverview,
  CarQuiz,
  CarQuizAdmin,
  CodeOfConduct,
  CodeOfConductAdmin,
  ExtraWork,
  ExtraWorkAdmin,
  RecruitmentDashboard,
  RecruitmentCandidates,
  CandidateDetail,
  RecruitmentMessages,
  SmsTemplates,
  EmailTemplatesPage,
  Winback,
  UpcomingInterviews,
  UpcomingHires,
  Some,
  TimeStamp,
  TestBoard,
  EconomicBoard,
  ClientSalesOverview,
  SalesDashboard,
  ClosingShifts,
  Permissions,
  RolePreview,
  LoginLog,
  TeamDashboard,
  FieldmarketingDashboardFull,
  CphSalesDashboard,
  TestDashboard,
  Messages,
} from "./pages";
import { SmartRedirect } from "./guards";

export const routes: RouteConfig[] = [
  { path: "/", component: SmartRedirect, access: "public" },
  { path: "/auth", component: Auth, access: "auth" },
  { path: "/onboarding", component: EmployeeOnboarding, access: "public" },
  { path: "/reset-password", component: ResetPassword, access: "public" },

  { path: "/home", component: Home, access: "protected" },
  { path: "/my-schedule", component: MySchedule, access: "protected" },
  { path: "/my-profile", component: MyProfile, access: "protected" },
  { path: "/my-contracts", component: MyContracts, access: "protected" },
  { path: "/pulse-survey", component: PulseSurvey, access: "protected" },
  { path: "/career-wishes", component: CareerWishes, access: "protected" },
  { path: "/car-quiz", component: CarQuiz, access: "protected" },
  { path: "/code-of-conduct", component: CodeOfConduct, access: "protected" },
  { path: "/time-stamp", component: TimeStamp, access: "protected" },
  { path: "/extra-work", component: ExtraWork, access: "protected" },
  { path: "/some", component: Some, access: "protected" },
  { path: "/messages", component: Messages, access: "protected" },

  { path: "/contract/:id", component: ContractSign, access: "public" },
  { path: "/contract/sign/:id", component: ContractSign, access: "public" },

  { path: "/dashboard", component: Dashboard, access: "role", positionPermission: "menu_dashboard" },
  { path: "/agents", component: Agents, access: "role", positionPermission: "menu_employees" },
  { path: "/sales", component: Sales, access: "role", positionPermission: "menu_sales" },
  { path: "/codan", component: Codan, access: "role", positionPermission: "menu_codan" },
  { path: "/tdc-erhverv", component: TdcErhverv, access: "role", positionPermission: "menu_tdc_erhverv" },
  { path: "/team-overview", component: TeamOverview, access: "role", positionPermission: "menu_mg_test" },
  
  { path: "/payroll", component: Payroll, access: "role", positionPermission: "menu_payroll" },
  { path: "/mg-test", component: MgTest, access: "role", positionPermission: "menu_mg_test" },
  { path: "/mg-test-dashboard", component: MgTestDashboard, access: "role", positionPermission: "menu_test_dashboard" },
  { path: "/km-test", component: KmTest, access: "role", positionPermission: "menu_km_test" },
  { path: "/adversus-data", component: AdversusData, access: "role", positionPermission: "menu_adversus_data" },
  { path: "/dialer-data", component: DialerData, access: "role", positionPermission: "menu_dialer_data" },
  { path: "/calls-data", component: CallsData, access: "role", positionPermission: "menu_calls_data" },
  { path: "/logikker", component: Logikker, access: "role", positionPermission: "menu_logics" },
  { path: "/employees", component: EmployeeMasterData, access: "role", positionPermission: "menu_employees" },
  { path: "/employees/:id", component: EmployeeDetail, access: "role", positionPermission: "menu_employees" },
  { path: "/login-log", component: LoginLog, access: "role", positionPermission: "menu_login_log" },
  
  { path: "/settings", component: Settings, access: "role", positionPermission: "menu_settings" },

  { path: "/vagt-flow", component: VagtFlowIndex, access: "role", positionPermission: "menu_fm_overview" },
  { path: "/vagt-flow/booking", component: VagtBookingManagement, access: "role", positionPermission: "menu_fm_book_week" },
  { path: "/vagt-flow/book-week", component: VagtBookWeek, access: "role", positionPermission: "menu_fm_book_week" },
  { path: "/vagt-flow/locations", component: VagtLocations, access: "role", positionPermission: "menu_fm_locations" },
  { path: "/vagt-flow/locations/:id", component: VagtLocationDetail, access: "role", positionPermission: "menu_fm_locations" },
  { path: "/vagt-flow/bookings", component: VagtBookings, access: "role", positionPermission: "menu_fm_bookings" },
  { path: "/vagt-flow/vehicles", component: VagtVehicles, access: "role", positionPermission: "menu_fm_vehicles" },
  { path: "/vagt-flow/time-off", component: VagtTimeOffRequests, access: "role", positionPermission: "menu_fm_time_off" },
  { path: "/vagt-flow/sales-registration", component: VagtSalesRegistration, access: "role", positionPermission: "menu_fm_sales_registration" },
  { path: "/vagt-flow/fieldmarketing-dashboard", component: VagtFieldmarketingDashboard, access: "role", positionPermission: "menu_fm_sales_registration" },
  { path: "/vagt-flow/billing", component: VagtBilling, access: "role", positionPermission: "menu_fm_billing" },
  { path: "/vagt-flow/min-uge", component: VagtMinUge, access: "protected" },

  { path: "/shift-planning", component: ShiftOverview, access: "role", positionPermission: "menu_shift_overview" },
  { path: "/shift-planning/my-schedule", component: MySchedule, access: "protected" },
  { path: "/shift-planning/absence", component: AbsenceManagement, access: "role", positionPermission: "menu_absence" },
  { path: "/shift-planning/time-tracking", component: TimeTracking, access: "role", positionPermission: "menu_time_tracking" },

  { path: "/extra-work-admin", component: ExtraWorkAdmin, access: "role", positionPermission: "menu_extra_work_admin" },
  { path: "/contracts", component: Contracts, access: "role", positionPermission: "menu_contracts" },
  { path: "/pulse-survey-results", component: PulseSurveyResults, access: "role", positionPermission: "menu_pulse_survey" },
  { path: "/career-wishes-overview", component: CareerWishesOverview, access: "role", positionPermission: "menu_career_wishes_overview" },
  { path: "/car-quiz-admin", component: CarQuizAdmin, access: "role", positionPermission: "menu_car_quiz_admin" },
  { path: "/code-of-conduct-admin", component: CodeOfConductAdmin, access: "role", positionPermission: "menu_coc_admin" },

  { path: "/recruitment", component: RecruitmentDashboard, access: "role", positionPermission: "menu_recruitment_dashboard" },
  { path: "/recruitment/candidates", component: RecruitmentCandidates, access: "role", positionPermission: "menu_candidates" },
  { path: "/recruitment/candidates/:id", component: CandidateDetail, access: "role", positionPermission: "menu_candidates" },
  { path: "/recruitment/messages", component: RecruitmentMessages, access: "role", positionPermission: "menu_messages" },
  { path: "/recruitment/sms-templates", component: SmsTemplates, access: "role", positionPermission: "menu_sms_templates" },
  { path: "/recruitment/email-templates", component: EmailTemplatesPage, access: "role", positionPermission: "menu_email_templates" },
  { path: "/recruitment/winback", component: Winback, access: "role", positionPermission: "menu_winback" },
  { path: "/recruitment/upcoming-interviews", component: UpcomingInterviews, access: "role", positionPermission: "menu_upcoming_interviews" },
  { path: "/recruitment/upcoming-hires", component: UpcomingHires, access: "role", positionPermission: "menu_upcoming_hires" },

  { path: "/boards/test", component: TestBoard, access: "public" },
  { path: "/boards/economic", component: EconomicBoard, access: "public" },
  { path: "/client-sales-overview", component: ClientSalesOverview, access: "role", positionPermission: "menu_sales" },
  { path: "/boards/sales", component: SalesDashboard, access: "public" },
  
  // Team Dashboards (full screen, no sidebar) - public access for TV displays
  { path: "/dashboards/cph-sales", component: CphSalesDashboard, access: "public" },
  { path: "/dashboards/fieldmarketing", component: FieldmarketingDashboardFull, access: "public" },
  { path: "/dashboards/tdc-erhverv", component: TdcErhvervDashboard, access: "public" },
  { path: "/dashboards/relatel", component: RelatelDashboard, access: "public" },
  { path: "/dashboards/tryg", component: TrygDashboard, access: "public" },
  { path: "/dashboards/ase", component: AseDashboard, access: "public" },
  { path: "/dashboards/mg-test", component: MgTestDashboard, access: "public" },
  { path: "/dashboards/test", component: TestDashboard, access: "public" },
  { path: "/dashboards/:teamSlug", component: TeamDashboard, access: "public" },
  
  { path: "/survey", component: PublicPulseSurvey, access: "public" },

  { path: "/closing-shifts", component: ClosingShifts, access: "role", positionPermission: "menu_closing_shifts" },

  { path: "/permissions", component: Permissions, access: "role", positionPermission: "menu_permissions" },
  { path: "/role-preview/:id", component: RolePreview, access: "role", positionPermission: "menu_permissions" },
  { path: "*", component: NotFound, access: "public" },
];
