-- 1) Transaktioner fra e-conomic
CREATE TABLE IF NOT EXISTS public.transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  amount numeric(14,2) NOT NULL,
  account_number text NOT NULL,
  text text,
  voucher_id text,
  type text NOT NULL CHECK (type IN ('expense','revenue')),
  category text,
  source_id text UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON public.transactions(type);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON public.transactions(category);

-- 2) Faste udgifter (plan/forecast)
CREATE TABLE IF NOT EXISTS public.fixed_costs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  amount numeric(14,2) NOT NULL,
  frequency text NOT NULL CHECK (frequency IN ('monthly','annual')),
  start_date date NOT NULL,
  end_date date,
  active boolean DEFAULT true,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fixed_costs_active ON public.fixed_costs(active);
CREATE INDEX IF NOT EXISTS idx_fixed_costs_dates ON public.fixed_costs(start_date, end_date);

-- 3) Mapping fra e-conomic konto -> kategori + type
CREATE TABLE IF NOT EXISTS public.accounts_map (
  account_number text PRIMARY KEY,
  category text NOT NULL,
  type text NOT NULL CHECK (type IN ('expense','revenue'))
);

-- 4) Sync-state så du kun henter nye entries
CREATE TABLE IF NOT EXISTS public.sync_state (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  last_sync_at timestamptz,
  last_entry_date date
);

INSERT INTO public.sync_state(id, last_sync_at, last_entry_date)
VALUES (1, now() - interval '7 days', current_date - 7)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fixed_costs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_state ENABLE ROW LEVEL SECURITY;

-- RLS policies for transactions
CREATE POLICY "Authenticated users can view transactions" 
ON public.transactions FOR SELECT 
USING (true);

CREATE POLICY "Managers can manage transactions" 
ON public.transactions FOR ALL 
USING (is_manager_or_above(auth.uid()));

-- RLS policies for fixed_costs
CREATE POLICY "Authenticated users can view fixed_costs" 
ON public.fixed_costs FOR SELECT 
USING (true);

CREATE POLICY "Managers can manage fixed_costs" 
ON public.fixed_costs FOR ALL 
USING (is_manager_or_above(auth.uid()));

-- RLS policies for accounts_map
CREATE POLICY "Authenticated users can view accounts_map" 
ON public.accounts_map FOR SELECT 
USING (true);

CREATE POLICY "Managers can manage accounts_map" 
ON public.accounts_map FOR ALL 
USING (is_manager_or_above(auth.uid()));

-- RLS policies for sync_state
CREATE POLICY "Authenticated users can view sync_state" 
ON public.sync_state FOR SELECT 
USING (true);

CREATE POLICY "Managers can manage sync_state" 
ON public.sync_state FOR ALL 
USING (is_manager_or_above(auth.uid()));