-- First, update the onboarding_drills table to include all new fields
ALTER TABLE public.onboarding_drills
ADD COLUMN IF NOT EXISTS when_to_use text,
ADD COLUMN IF NOT EXISTS setup text,
ADD COLUMN IF NOT EXISTS steps jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS reps integer,
ADD COLUMN IF NOT EXISTS script_snippets jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS success_criteria jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS common_mistakes jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS variants jsonb DEFAULT '[]'::jsonb;

-- Clear existing drills
DELETE FROM public.onboarding_drills;

-- Insert all drills
INSERT INTO public.onboarding_drills (id, title, focus, duration_min, description, when_to_use, setup, steps, reps, script_snippets, success_criteria, common_mistakes, variants) VALUES
('OPENING_TO_QUESTION', 'Åbning → første behovsspørgsmål', 'B', 6, 'Når sælger tøver i starten, virker nervøs, eller starter med pitch.', 'Når sælger tøver i starten, virker nervøs, eller starter med pitch.', 'Stå op eller sid ret. Smil i stemmen. Hav 1 behovsspørgsmål klar.', '["Sig: \"Hej, det er [navn] fra [virksomhed] – har jeg ringet på et okay tidspunkt?\"", "Vent 1 sekund (ingen fyldord).", "Sig: \"Super – må jeg stille dig et par hurtige spørgsmål?\"", "Stil ét behovsspørgsmål (vælg ét af dine scripts nedenfor).", "Hold en pause og lyt."]'::jsonb, 15, '["Hvordan gør I det i dag?", "Hvad bruger I typisk på [område]?", "Hvad er vigtigst for jer, når det kommer til [X]?"]'::jsonb, '["15 gentagelser uden at snuble", "Du går ikke direkte til pitch", "Du holder pause efter spørgsmålet"]'::jsonb, '["Undskylder for opkaldet", "Taler for længe før første spørgsmål", "Fylder stilhed ud"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('STRUCTURED_OPENING', 'Struktureret åbning (ramme på 15 sek)', 'Struktur', 6, 'Når samtaler starter rodet eller sælger mister kontrol tidligt.', 'Når samtaler starter rodet eller sælger mister kontrol tidligt.', 'Hav ''årsag'' klar i én sætning.', '["Sig åbningen højt som én kort blok:", "\"Jeg ringer kort fordi [årsag]. Det tager 2 minutter, og hvis det ikke er relevant, stopper vi bare – okay?\"", "Hold 1 sekund pause.", "Gentag igen med ny ''årsag''."]'::jsonb, 10, '["Jeg ringer kort fordi vi hjælper med [outcome]. Det tager 2 minutter, og hvis det ikke er relevant, stopper vi bare – okay?"]'::jsonb, '["Åbningen er kort og rolig", "Ingen undskyldning / overforklaring"]'::jsonb, '["Bliver for lang", "Lyder usikker: \"øh, jeg ved godt...\""]'::jsonb, '["solo", "buddy", "manager-led"]'::jsonb),

('QUESTION_LADDER', 'Spørgestigen (åbent → konkret → konsekvens)', 'B', 8, 'Når behovet bliver for overfladisk, eller sælger ikke får noget at bygge løsning på.', 'Når behovet bliver for overfladisk, eller sælger ikke får noget at bygge løsning på.', 'Vælg et emne/produktområde og 1 kundetype.', '["Åbent spørgsmål: \"Hvordan gør I det i dag?\"", "Konkret opfølgning: \"Hvor ofte oplever I det?\"", "Konsekvens: \"Hvad betyder det for jer i hverdagen?\"", "Stop – lyt – skriv 3 nøgleord ned."]'::jsonb, 10, '["Hvordan gør I det i dag?", "Hvor ofte oplever I det?", "Hvad betyder det for jer i hverdagen?"]'::jsonb, '["Du når konsekvensspørgsmålet hver gang", "Du lytter uden at afbryde"]'::jsonb, '["Springer direkte til løsning", "Stiller 5 spørgsmål uden at lytte"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('EFU_LADDER', 'EFU (Emotion/Følge/Udfald) uden at blive tung', 'B', 8, 'Når kunden svarer kort og behovet ikke ''bider''.', 'Når kunden svarer kort og behovet ikke ''bider''.', 'Vælg 2 EFU-spørgsmål du kan lide.', '["Stil et EFU-spørgsmål: \"Hvordan påvirker det dig?\"", "Opfølgning: \"Hvad betyder det for jer?\"", "Stop og lyt. Gentag med et nyt scenario."]'::jsonb, 10, '["Hvordan påvirker det dig?", "Hvad betyder det for jer?", "Hvordan føles det, når det sker?"]'::jsonb, '["Du får et mere personligt/konsekvensbaseret svar", "Du går ikke i pitch-mode"]'::jsonb, '["Overdriver (bliver dramatisk)", "Skifter emne for hurtigt"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('NEEDS_SUMMARY_7SEC', 'Opsummer behov på 7–10 sek + få accept', 'A', 6, 'Når sælger pitcher uden at have kundens accept på behov.', 'Når sælger pitcher uden at have kundens accept på behov.', 'Skriv 3 eksempel-behov ned.', '["Sig: \"Så hvis jeg forstår dig rigtigt, så [1 kort sætning]. Er det fair?\"", "Hold pause og vent på svar.", "Gentag med næste behov."]'::jsonb, 20, '["Så hvis jeg forstår dig rigtigt, så vil du gerne [behov], fordi [konsekvens]. Er det fair?"]'::jsonb, '["Du bruger maks 1 sætning", "Du holder kæft efter ''fair?''"]'::jsonb, '["Forklarer mere efter opsummeringen", "Laver opsummeringen for lang"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('OBJECTION_PING_PONG', 'Indvending ping-pong (anerkend → spørg → tilbage til behov)', 'B/A', 10, 'Når sælger argumenterer eller mister ro ved indvendinger.', 'Når sælger argumenterer eller mister ro ved indvendinger.', 'Hav jeres top-10 indvendinger klar.', '["Anerkend: \"Det giver god mening\"", "Spørg: \"Hvad ligger der bag det?\"", "Tilbage til behov: \"Så det handler om [X] – korrekt?\"", "Gentag med næste indvending."]'::jsonb, 15, '["Det giver god mening. Må jeg spørge: hvad ligger der bag det?", "Okay — hvad skulle der til, for at det blev relevant?"]'::jsonb, '["Du stiller altid et spørgsmål", "Du argumenterer ikke"]'::jsonb, '["Forklarer for meget", "Går i forsvar"]'::jsonb, '["solo", "buddy", "manager-led"]'::jsonb),

('PRICE_DEFUSE', 'Pris uden panik (dyrt → tilbage til værdi)', 'B/A', 10, 'Når kunden siger ''det er dyrt'' eller sælger bliver defensiv.', 'Når kunden siger ''det er dyrt'' eller sælger bliver defensiv.', 'Vælg 1 standardsætning til pris.', '["Sig: \"Helt fair – må jeg spørge: hvad sammenligner du det med?\"", "Opfølg: \"Og hvad koster det jer, hvis I ikke gør noget?\"", "Tilbage til behov: \"Så det du gerne vil undgå er [X] – korrekt?\""]'::jsonb, 10, '["Helt fair – hvad sammenligner du det med?", "Hvad koster det jer, hvis I ikke gør noget?"]'::jsonb, '["Ingen rabat-refleks", "Du kobler pris til behov/outcome"]'::jsonb, '["Tilbyder rabat for tidligt", "Går i argumentation"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('VALUE_BRIDGE_20SEC', 'Value bridge på 20 sek (behov → løsning → effekt)', 'L', 6, 'Når sælger feature-dumper eller pitcher uden kobling til behov.', 'Når sælger feature-dumper eller pitcher uden kobling til behov.', 'Vælg 3 typiske behov og skriv en bridge til hver.', '["Sig skabelonen højt (stop efter 20 sek):", "\"Fordi du sagde [behov], giver [løsning] mening, så du får [outcome].\"", "Spørg mini-accept: \"Giver det mening?\"", "Hold pause."]'::jsonb, 15, '["Fordi du sagde [behov], giver [løsning] mening, så du får [outcome]. Giver det mening?"]'::jsonb, '["Max 20 sek pitch", "Tydelig kobling til behov", "Mini-accept + stilhed"]'::jsonb, '["Bliver for lang", "Glemmer outcome"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('MINI_ACCEPT_AFTER_PITCH', 'Mini-accept efter pitch (ingen overforklaring)', 'A', 5, 'Når sælger taler videre i stedet for at få kundens accept.', 'Når sælger taler videre i stedet for at få kundens accept.', 'Hav én pitch-sætning klar.', '["Sig pitch (kort).", "Spørg: \"Giver det mening?\"", "Hold pause (2 sek).", "Gentag."]'::jsonb, 15, '["Giver det mening?"]'::jsonb, '["Du holder pause", "Du forklarer ikke mere efter spørgsmålet"]'::jsonb, '["Fylder stilheden ud"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('ASK_FOR_THE_ORDER', 'Spørg om køb (tydeligt + stilhed)', 'A', 6, 'Når sælger ikke får bedt om accept/køb.', 'Når sælger ikke får bedt om accept/køb.', 'Vælg 1 af jeres 3 standard-asks.', '["Vælg én ask og sig den højt.", "Hold pause (2 sek).", "Gentag med næste scenario."]'::jsonb, 20, '["Skal vi sætte det i gang?", "Giver det mening, at vi starter i dag?", "Skal vi tage næste skridt nu?"]'::jsonb, '["20 asks uden undskyldning", "Ingen forklaring efter ask"]'::jsonb, '["Overforklarer", "Lyder undskyldende"]'::jsonb, '["solo", "buddy", "manager-led"]'::jsonb),

('ASSUMPTIVE_CLOSE', 'Antagelse (rolig lukning med dato)', 'A', 6, 'Når sælger har momentum og kunden viser accept, men der mangler closing.', 'Når sælger har momentum og kunden viser accept, men der mangler closing.', 'Vælg en dato/valg (fx ''i dag'' eller ''på mandag'').', '["Sig: \"Så vi starter [dato], og jeg sender bekræftelse – okay?\"", "Hold pause.", "Gentag."]'::jsonb, 15, '["Så vi starter [dato], og jeg sender bekræftelse – okay?"]'::jsonb, '["Du siger det roligt", "Du låser et valg/dato"]'::jsonb, '["Lyder pressende", "Glemmer pause"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('CLOSE_ON_SIGNAL', 'Luk på købssignal inden 5 sek', 'A', 8, 'Når kunden giver delaccept/købssignal og sælger fortsætter med at forklare.', 'Når kunden giver delaccept/købssignal og sælger fortsætter med at forklare.', 'Hav 10 købssignaler skrevet ned.', '["Læs et købssignal højt (som kunden).", "Svar inden 5 sek: \"Perfekt – skal vi sætte det i gang?\"", "Hold pause og gentag."]'::jsonb, 10, '["Perfekt – skal vi sætte det i gang?", "Fedt – skal vi starte nu så?"]'::jsonb, '["Du går til ask hurtigt", "Ingen ekstra forklaring"]'::jsonb, '["Taler videre", "Skifter emne"]'::jsonb, '["solo", "buddy", "manager-led"]'::jsonb),

('QUALIFIED_CALLBACK', 'Callback der er kvalificeret (tid + agenda + kriterie)', 'Flow', 8, 'Når callbacks bliver en undskyldning for ikke at lukke eller ender som ''løse ender''.', 'Når callbacks bliver en undskyldning for ikke at lukke eller ender som ''løse ender''.', 'Vælg 2 tidspunkter du kan tilbyde (fx i morgen 14:00 eller 16:30).', '["Sig: \"Hvad mangler for at du kan sige ja?\"", "Sig: \"Hvad skal du tage stilling til, når vi taler igen?\"", "Book: \"Skal vi tage den i morgen kl. 14:00 eller 16:30?\"", "Gentag."]'::jsonb, 10, '["Hvad mangler for at du kan sige ja?", "Hvad skal du tage stilling til, når vi taler igen?", "Skal vi tage den i morgen kl. 14:00 eller 16:30?"]'::jsonb, '["Alle callbacks har tid + agenda", "Du får et ''kriterie'' for ja"]'::jsonb, '["Callback uden tid", "Sender materiale uden next step"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('CLEAN_PIPELINE', 'Clean pipeline (ingen samtale uden næste step)', 'Struktur', 5, 'Når opfølgninger flyder og CRM bliver rodet.', 'Når opfølgninger flyder og CRM bliver rodet.', 'Hav jeres dispositionsliste klar.', '["Tag 10 mini-cases (ja / nej / callback).", "For hver case: vælg disposition + næste step (tid/dato hvis callback).", "Skriv én sætning ''hvad sker der nu''."]'::jsonb, 10, '["Perfekt — næste step er [X] på [dato/klok].", "Fair — så stopper vi her. Tak for tiden."]'::jsonb, '["10 cases med klart næste step", "Intet efterlades åbent"]'::jsonb, '["Uklare aftaler", "Ingen tid/dato"]'::jsonb, '["solo", "manager-led"]'::jsonb),

('RESET_AFTER_NO', 'Reset efter nej (10 sek ritual)', 'Mindset', 3, 'Når sælger mister energi efter afvisninger og tempoet falder.', 'Når sælger mister energi efter afvisninger og tempoet falder.', 'Stå op 10 sek.', '["Træk vejret ind (4 sek) og ud (4 sek).", "Sig højt: \"Næste kald er et nyt menneske.\"", "Klik ring igen."]'::jsonb, 10, '["Næste kald er et nyt menneske."]'::jsonb, '["Du kan gøre det uden at tænke", "Du kommer hurtigt i gang igen"]'::jsonb, '["Scroller telefon/CRM for længe", "Tænker på sidste nej"]'::jsonb, '["solo"]'::jsonb);